//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTools.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBTools.Templates.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;title&gt;&lt;/title&gt;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Tables}.
        /// </summary>
        internal static string install_mysql_utf8 {
            get {
                return ResourceManager.GetString("install_mysql_utf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////**
        /// * @version     $Id: script.php 
        /// * @package		{NameExtension}
        /// * @copyright	Copyright (C) {CopyrightAno} Doria TI. All rights reserved.
        /// * @license		Comercial 
        /// */
        ///// No direct access to this file
        ///defined(&apos;_JEXEC&apos;) or die(&apos;Restricted access&apos;);
        ////**
        /// * Install Script file of {Name} component
        /// */
        ///class {NameExtension}InstallerScript
        ///{
        ///	/**
        ///	 * method to install the component
        ///	 *
        ///	 * @return void
        ///	 */
        ///	function install($parent) 
        ///	{
        ///		
        ///	}
        /// 
        ///	/**
        ///	 * method to uninstall the component
        ///	 *
        ///	 * @return voi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JoomlaScript {
            get {
                return ResourceManager.GetString("JoomlaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;extension method=&quot;{Method}&quot; type=&quot;{Type}&quot; version=&quot;3&quot;&gt;
        ///  &lt;name&gt;{NameExtension}&lt;/name&gt;
        ///  &lt;author&gt;Doria TI&lt;/author&gt;
        ///  &lt;creationDate&gt;{CreationDate}&lt;/creationDate&gt;
        ///  &lt;copyright&gt;(C) {CopyrightAno}&lt;/copyright&gt;
        ///  &lt;license&gt;Comercial&lt;/license&gt;
        ///  &lt;authorEmail&gt;contato@doriati.com.br&lt;/authorEmail&gt;
        ///  &lt;authorUrl&gt;www.doriati.com.br&lt;/authorUrl&gt;
        ///  &lt;version&gt;{Version}&lt;/version&gt;
        ///  &lt;description&gt;COM__XML_DESCRIPTION&lt;/description&gt;
        ///  &lt;!-- Runs on install/uninstall/update --&gt;
        ///  &lt;scriptfile&gt;sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JoomlaTemplateXML {
            get {
                return ResourceManager.GetString("JoomlaTemplateXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;extension type=&quot;package&quot; version=&quot;3.0&quot; method=&quot;{Method}&quot;&gt;
        ///  &lt;name&gt;{Name}&lt;/name&gt;
        ///  &lt;packagename&gt;{Packagename}&lt;/packagename&gt;
        ///  &lt;creationDate&gt;{CreationDate}&lt;/creationDate&gt;
        ///  &lt;author&gt;Doria TI&lt;/author&gt;
        ///  &lt;copyright&gt;(C) {CopyrightAno}&lt;/copyright&gt;
        ///  &lt;license&gt;Comercial&lt;/license&gt;
        ///  &lt;authorEmail&gt;contato@doriati.com.br&lt;/authorEmail&gt;
        ///  &lt;authorUrl&gt;https://www.doriati.com.br&lt;/authorUrl&gt;
        ///  &lt;version&gt;{Version}&lt;/version&gt;
        ///  &lt;packager&gt;Doria TI&lt;/packager&gt;
        ///  &lt;packagerurl&gt;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JoomlaTemplateXMLPackageNew {
            get {
                return ResourceManager.GetString("JoomlaTemplateXMLPackageNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;install&gt;
        ///    &lt;sql&gt;
        ///      &lt;file charset=&quot;utf8&quot; driver=&quot;mysql&quot;&gt;sql/install.mysql.utf8.sql&lt;/file&gt;
        ///    &lt;/sql&gt;
        ///  &lt;/install&gt;
        ///  &lt;uninstall&gt;
        ///    &lt;sql&gt;
        ///      &lt;file charset=&quot;utf8&quot; driver=&quot;mysql&quot;&gt;sql/uninstall.mysql.utf8.sql&lt;/file&gt;
        ///    &lt;/sql&gt;
        ///  &lt;/uninstall&gt;.
        /// </summary>
        internal static string JoomlaTemplateXMLScripts {
            get {
                return ResourceManager.GetString("JoomlaTemplateXMLScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE  {Tables}.
        /// </summary>
        internal static string uninstall_mysql_utf8 {
            get {
                return ResourceManager.GetString("uninstall_mysql_utf8", resourceCulture);
            }
        }
    }
}
